mapping_directory = "../mappings"
schemas_directory = "../venv/lib/python3.14/site-packages/tokamap/schemas"
trace_enabled = false
cache_enabled = false
custom_function_libraries = []

[data_source_factories]
uda_factory = "../libuda_data_source_debug.dylib"

[data_sources.UDA]
factory = "uda_factory"
args.host = "uda2.hpc.l"
args.port = 59876
args.plugin_name = "UDA"
